port = 8080
port = ${?PORT}

admin-port = 8081
admin-port = ${?ADMIN_PORT}

db-path = "./data/pellegrino.db"
db-path = ${?DB_PATH}

discord-client-id = "dev-unset"
discord-client-id = ${?DISCORD_CLIENT_ID}
discord-client-secret = "dev-unset"
discord-client-secret = ${?DISCORD_CLIENT_SECRET}

discord-redirect-uri = "http://localhost:8080/api/auth/discord/callback"
discord-redirect-uri = ${?DISCORD_REDIRECT_URI}
